#-------------------------------
# General Site Settings

menu:
- {name: 'Works',          url: ''}
- {name: 'Research & Press', url: 'research'}
- {name: 'About',          url: 'about'}
- {name: 'Contact',        url: 'contact'}

#-------------------------------
# Projects Section (Works)

projects:
- {name: 'Art Work', url: 'art-work', folder: 'art-work'}
- {name: 'Film',     url: 'film',     folder: 'film'}

#-------------------------------
# Contact Section

social:
- {icon: 'envelope',  link: 'mailto:jingxi@yedianyang.com'}
- {icon: 'linkedin',  link: 'https://linkedin.com/in/jingxiguo'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' / 'linkedin' / 'youtube' / 'instagram' / 'soundcloud'

#-------------------------------
# SEO Section

seo:
  description: 'Jingxi Guo is a sound artist, sound engineer, and creative technologist. Graduate from Beijing Film Academy and NYU Tisch ITP.'
  rel-author: ''
  rel-publisher: ''

